<div class="row">
	<div class="col">
		<?php echo $this->partial('base/subtable', [
		    'title' => $this->dept->NAME,
		    'data' => $this->employees,
		    'primary_key' => 'UUID',
		    'route' => 'timecard/timesheet',
		    'params' => [
		        [
    		        'action' => 'timesheet',
    		        'label' => 'Open Timesheet',
    		        'route' => 'timecard/timesheet',
    		        'key' => 'UUID',
	            ]
		    ],
		]);?>
	</div>
</div>