<div class="row">
	<div class="col">
		<h1>Dashboard</h1>
	</div>
	<div class="col">
		<?php $week_form->setAttribute('action', $this->url('dept/default', ['action' => 'filter'])); ?>
		<?php $week_form->prepare(); ?>
		<?php echo $this->form()->openTag($week_form); ?>
		<div class="form-group">
			<?php echo $this->formRow($this->week_form->get('EMP_UUID')); ?>
			<?php echo $this->formRow($this->week_form->get('WORK_WEEK')); ?>
			<?php echo $this->formRow($this->week_form->get('SECURITY')); ?>
			<?php echo $this->formRow($this->week_form->get('SUBMIT')); ?>
		</div>
		<?php echo $this->form()->closeTag($week_form); ?>
	</div>
</div>	


<?php $title = $this->dept->NAME; ?>
<div class="row">
	<div class="col">
		<?php echo $this->partial('base/subtable', [
		    'title' => $title,
		    'data' => $this->employees,
		    'primary_key' => 'UUID',
		    'route' => 'timecard/timesheet',
		    'params' => [
		        [
    		        'action' => 'timesheet',
    		        'label' => 'Open Timesheet',
    		        'route' => 'timecard/timesheet',
    		        'key' => 'UUID',
	            ],
		        [
		            'action' => 'prepare',
		            'label' => 'Prepare',
		            'route' => 'timecard/secure_signatures',
		            'key' => 'UUID',
		        ],
		    ],
		]);?>
	</div>
</div>