<?php $title = $this->dept->NAME; ?>
<div class="row">
	<div class="col">
		<?php echo $this->partial('base/subtable', [
		    'title' => $title,
		    'data' => $this->employees,
		    'primary_key' => 'UUID',
		    'route' => 'timecard/timesheet',
		    'params' => [
		        [
    		        'action' => 'timesheet',
    		        'label' => 'Open Timesheet',
    		        'route' => 'timecard/timesheet',
    		        'key' => 'UUID',
	            ]
		    ],
		]);?>
	</div>
	<div class="col">
		<?php echo $this->partial('timecard/partials/signature.phtml'); ?>
	</div>
	
</div>
<?php if ($this->role == 'APP - CHRONOS DEPT HEAD') :?>
<div class="row">
	<div class="col">
		<?php echo $this->partial('timecard/partials/signature.phtml'); ?>
	</div>
</div>
<?php endif;?>