<?php
global $report_data;
global $work_week;

$report_data = [];
$pay_types = ['Regular','Overtime','Premium','Unproductive','Other/Unpaid'];
$dow = ['MON','TUE','WED','THU','FRI','SAT','SUN', 'DAYS'];

foreach ($this->data as $record) {
    if (!isset($work_week)) {
        $work_week = $record['WORK_WEEK'];
    }
    
    $index = sprintf('%s-%s', $record['EMP_NUM'], $record['CODE']);
    $report_data[$index] = [
        'RECORD' => $record,
    ];
}

sort($report_data);

echo $this->partial('timecard/reports/report_header.phtml', [
    'user' => $this->currentUser(),
    'work_week' => $work_week,
]);
?>
<table class="table table-sm">
	<thead>
		<tr>
			<td>Employee Number</td>
    		<td>First Name</td>
    		<td>Last Name</td>
    		<td>Pay Code</td>
		<?php foreach ($dow as $day) : ?>
			<td><?=$day?></td>
		<?php endforeach; ?>
			<td>Total</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($report_data as $employee) : ?>
		<?php $total = 0; ?>
		<tr>
			<td><?=$employee['RECORD']['EMP_NUM']?></td>
			<td><?=$employee['RECORD']['FNAME']?></td>
			<td><?=$employee['RECORD']['LNAME']?></td>
			<td><?=$employee['RECORD']['CODE']?></td>
			<?php foreach ($dow as $day) : ?>
			<td><?=$employee['RECORD'][$day]?></td>
			<?php $total += $employee['RECORD'][$day]; ?>
			<?php endforeach; ?>
			<td><?=$total;?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>