<div class="container">
    <div class="row">
    	<div class="col-2">
    		<img src="<?= $this->basePath('img/cityseal.png') ?>" height="100px" alt="Middletown, CT" />
    	</div>
    	<div class="col-7">
    		<h1>City of Middletown</h1>
    	</div>
    	<div class="col-3">
    		Week Ending: <?=$this->work_week; ?>
    	</div>
    </div>
    <div class="row">
    	<div class="col-9">&nbsp;</div>
    	
    </div>
</div>