<?php
use Timecard\Model\TimecardModel;
?>
<div class="row">
	<div class="col-9">
		<h1><?php echo sprintf('%s %s - Timesheet', $this->user_entity->employee->FNAME, $this->user_entity->employee->LNAME)?></h1>
	</div>
	<div class="col-3">
		<?php $week_form->setAttribute('action', $this->url('timecard/default', ['action' => 'filter'])); ?>
		<?php $week_form->prepare(); ?>
		<?php echo $this->form()->openTag($week_form); ?>
		<div class="form-group">
			<?php echo $this->formRow($this->week_form->get('EMP_UUID')); ?>
			<?php echo $this->formRow($this->week_form->get('WORK_WEEK')); ?>
			<?php echo $this->formRow($this->week_form->get('SECURITY')); ?>
			<?php echo $this->formRow($this->week_form->get('SUBMIT')); ?>
		</div>
		<?php echo $this->form()->closeTag($week_form); ?>
	</div>
</div>		

<div class="row">
	<div class="col">
	
	<!-- SM Viewport -->
	<div class="d-block d-lg-none">
			<?php foreach ($this->timesheet_forms as $form) : ?>
				<?php $var = $form->get('STATUS')->getValue(); ?>
				<?php echo $this->partial('timecard/timecard/xs/paycode.phtml',['form' => $form, 'user' => $this->user, 'acl_service' => $this->acl_service]); ?>
			<?php endforeach; ?>
			
		<!-- Add Pay Code Form -->
		<div class="container">
		<div class="row">
    		<?php $this->timecard_add_form->setAttribute('action', $this->url('timecard/default', ['action' => 'addPayCode']));?>
    		<?php $this->timecard_add_form->prepare(); ?>
    		<?php echo $this->form()->openTag($this->timecard_add_form); ?>
    			<?php echo $this->formRow($this->timecard_add_form->get('TIMECARD_UUID')); ?>
    			<?php echo $this->formRow($this->timecard_add_form->get('SECURITY')); ?>
    		<div class="col-xxs-4">
    			Add New Pay Code:
    		</div>
    		<div class="col-xxs-6">
    			<?php echo $this->formSelect($this->timecard_add_form->get('PAY_UUID')); ?>
    		</div>
    		<div class="col-xxs-2">
    			<?php echo $this->formRow($this->timecard_add_form->get('SUBMIT')); ?>
    		</div>
    		<?php echo $this->form()->closeTag($this->timecard_add_form); ?>
		</div>
		</div>
	</div>
	
	<!-- MD Viewport -->
	<div class="table-responsive-lg d-none d-lg-block d-xl-none">
		<table class="table table-sm">
			<thead class="table-dark">
				<tr>
					<th scope="col">Pay&nbsp;Code</th>
					<th scope="col">Mon</th>
					<th scope="col">Tue</th>
					<th scope="col">Wed</th>
					<th scope="col">Thu</th>
					<th scope="col">Fri</th>
					<th scope="col">Sat</th>
					<th scope="col">Sun</th>
					<th scope="col">Days</th>
					<th scope="col">Total<th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->timesheet_forms as $form) : ?>
				<?php $var = $form->get('STATUS')->getValue(); ?>
				<?php echo $this->partial('timecard/timecard/md/paycode.phtml',['form' => $form, 'user' => $this->user, 'acl_service' => $this->acl_service]); ?>
			<?php endforeach; ?>
			<tr>
				<td>Daily Totals</td>
				<?php foreach (['MON','TUE','WED','THU','FRI','SAT','SUN'] as $DAY) : ?>
				<td>
					<?php 
					switch (TRUE) {
					    case (floatval($this->HOURS[$DAY]) == 0):
					        $total_class = 'text-bg-success';
					        break;
					    case (floatval($this->HOURS[$DAY]) > 8):
					    case (floatval($this->HOURS[$DAY]) < 8):
					        $total_class = 'text-bg-warning';
					        break;
					    default:
					        $total_class = 'text-bg-success';
					        break;
					}
					   echo "<span class='badge $total_class'>" . $this->HOURS[$DAY] . "</span>"; 
					?>
				</td>
				<?php endforeach; ?>
				<td />
				<td>
					<?php 
					if ($this->HOURS['TOTAL'] > 40 || $this->HOURS['TOTAL'] < 40 ) {
					    echo "<span class='badge text-bg-warning'>" . $this->HOURS['TOTAL'] . "</span>";
					} else {
// 					    echo "<span class='badge text-bg-success'>" . $this->HOURS['TOTAL'] . "</span>";
					}
					?>
				</td>
			</tr>
			</tbody>
			<tfoot>
				<tr>
					<?php $this->timecard_add_form->setAttribute('action', $this->url('timecard/default', ['action' => 'addPayCode']));?>
					<?php $this->timecard_add_form->prepare(); ?>
					<?php echo $this->form()->openTag($this->timecard_add_form); ?>
						<?php echo $this->formRow($this->timecard_add_form->get('TIMECARD_UUID')); ?>
						<?php echo $this->formRow($this->timecard_add_form->get('SECURITY')); ?>
					<td colspan="2">
						Add New Pay Code:
					</td>
					<td colspan="6">
						<?php echo $this->formSelect($this->timecard_add_form->get('PAY_UUID')); ?>
					</td>
					<td>
						<?php echo $this->formRow($this->timecard_add_form->get('SUBMIT')); ?>
					</td>
					<?php echo $this->form()->closeTag($this->timecard_add_form); ?>
				</tr>
			</tfoot>
		</table>
	</div>
	
	<!-- XL Viewport -->
	<div class="table-responsive-lg d-none d-xl-block">
		<table class="table table-sm">
			<thead class="table-dark">
				<tr>
					<th scope="col">Pay&nbsp;Code</th>
					<th scope="col">Mon</th>
					<th scope="col">Tue</th>
					<th scope="col">Wed</th>
					<th scope="col">Thu</th>
					<th scope="col">Fri</th>
					<th scope="col">Sat</th>
					<th scope="col">Sun</th>
					<th scope="col">Days</th>
					<th scope="col">Total<th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->timesheet_forms as $form) : ?>
				<?php $var = $form->get('STATUS')->getValue(); ?>
				<?php echo $this->partial('timecard/timecard/xl/paycode.phtml',['form' => $form, 'user' => $this->user, 'acl_service' => $this->acl_service]); ?>
			<?php endforeach; ?>
			<tr>
				<td>Daily Totals</td>
				<?php foreach (['MON','TUE','WED','THU','FRI','SAT','SUN'] as $DAY) : ?>
				<td>
					<?php 
					switch (TRUE) {
					    case (floatval($this->HOURS[$DAY]) == 0):
					        $total_class = 'text-bg-success';
					        break;
					    case (floatval($this->HOURS[$DAY]) > 8):
					    case (floatval($this->HOURS[$DAY]) < 8):
					        $total_class = 'text-bg-warning';
					        break;
					    default:
					        $total_class = 'text-bg-success';
					        break;
					}
					   echo "<span class='badge $total_class'>" . $this->HOURS[$DAY] . "</span>"; 
					?>
				</td>
				<?php endforeach; ?>
				<td />
				<td>
					<?php 
					if ($this->HOURS['TOTAL'] > 40 || $this->HOURS['TOTAL'] < 40 ) {
					    echo "<span class='badge text-bg-warning'>" . $this->HOURS['TOTAL'] . "</span>";
					} else {
// 					    echo "<span class='badge text-bg-success'>" . $this->HOURS['TOTAL'] . "</span>";
					}
					?>
				</td>
			</tr>
			</tbody>
			<tfoot>
				<tr>
					<?php $this->timecard_add_form->setAttribute('action', $this->url('timecard/default', ['action' => 'addPayCode']));?>
					<?php $this->timecard_add_form->prepare(); ?>
					<?php echo $this->form()->openTag($this->timecard_add_form); ?>
						<?php echo $this->formRow($this->timecard_add_form->get('TIMECARD_UUID')); ?>
						<?php echo $this->formRow($this->timecard_add_form->get('SECURITY')); ?>
					<td colspan="2">
						Add New Pay Code:
					</td>
					<td colspan="6">
						<?php echo $this->formSelect($this->timecard_add_form->get('PAY_UUID')); ?>
					</td>
					<td>
						<?php echo $this->formRow($this->timecard_add_form->get('SUBMIT')); ?>
					</td>
					<?php echo $this->form()->closeTag($this->timecard_add_form); ?>
				</tr>
			</tfoot>
		</table>
	</div>
	</div>
</div>

<div class="row">
	<?php if ($var != TimecardModel::COMPLETED_STATUS) : ?>
	<div class="col"><?php echo $this->subtable(['title' => 'Leave Information','params' => [],'primary_key' => 'UUID', 'data' => $leave_totals, 'help' => $this->help_leave]); ?></div>
	<?php endif; ?>
	<div class="col mb-4"><?php $this->boxFiles()->setTitle($this->files_title)->setData($this->files)->setReference($this->files_reference)->setVariable('actionMenu', $actionMenu)->render(); ?></div>
	<div class="col">
		<?php
		$roles = [];
		foreach ($this->user->memberOf() as $role) {
		    array_push($roles, $role['ROLENAME']);
		}
		
		echo $this->partial('timecard/partials/sign.phtml', [
		    'title' => 'Signatures',
		    'data' => $this->timecard_signatures,
		    'primary_key' => 'UUID',
		    'route' => 'timecards/signatures',
		    'timecard_uuid' => $this->timecard_uuid,
		    'role' => $roles,
		    'acl_service' => $acl_service,
		    'params' => [],
		]); 
		?>
	</div>
</div>
<?php echo $this->annotations()->setAnnotations($this->annotations)->render(); ?>
