<?php 
/**
 * Passed Variables
 * form, user_entity, acl_service
 */
use Components\Form\Element\DatabaseSelect;
use Timecard\Model\TimecardLineModel;

$uuid= $form->get('UUID')->getValue();
$form->setAttribute('action', $this->url('timecard/lines', ['action' => 'update', 'uuid' => $uuid]));
$form->prepare();

echo $this->form()->openTag($form);

$paycode = $form->get('PAY_UUID');
$paycode_value_options = $paycode->getValueOptions();
$paycode_value = $paycode->getValue();

echo $this->formInput($form->get('UUID'));
echo $this->formInput($form->get('SECURITY'));
echo $this->formInput($form->get('TIMECARD_UUID'));

$cols = ['MON','TUE','WED','THU','FRI','SAT','SUN','DAYS'];
$total_paycode = 0;
?>
<tr>
	<td colspan="12"><span style="white-space:nowrap"><?php echo $paycode_value_options[$paycode_value];?></span></td></tr>
	
<tr>
	<td></td>

	<?php foreach ($cols as $col) : ?>
		<?php $total_paycode += $form->get($col)->getValue(); ?>
			
    	<?php if ($this->acl_service->isAllowed($this->user->memberOf(TRUE), 'TIMECARD_LINE', $this->form->get('STATUS')->getValue())) : ?>
    		<td style="width: 72px;"><?php echo $this->formInput($form->get($col));?></td>
		<?php else : ?>
    		<td style="width: 72px;"><?php echo $form->get($col)->getValue(); ?></td>
    	<?php endif; ?>

	<?php endforeach; ?>
	<td>
		<?php 
		if ($total_paycode > 40) {
		    echo "<span class='badge badge-warning'>" . $total_paycode . "</span>";
		} else {
		    echo "<span class='badge badge-success'>" . $total_paycode . "</span>";
		}
        ?>
	</td>
	<td>
		<?php if ($this->acl_service->isAllowed($this->user->memberOf(TRUE), 'TIMECARD_LINE', $this->form->get('STATUS')->getValue())) : ?>
		<a href="<?php echo $this->url('timecard/lines', ['action' => 'delete', 'uuid' => $form->get('UUID')->getValue()]); ?>"><i class="fas fa-trash-alt"></i></a>
		<?php endif; ?>
	</td>
</tr>
<?php echo $this->formInput($form->get('SUBMIT'));?>
<?php echo $this->form()->closeTag($form); ?>