<div class="row">
	<div class="col-9">
		<h1>Department Dashboard</h1>
	</div>
	<div class="col-3">
		<?php $week_form->setAttribute('action', $this->url('dashboard/department', ['uuid' => '00000000-0000-0000-0000-000000000000', 'week' => $this->work_week])); ?>
		<?php $week_form->prepare(); ?>
		<?php echo $this->form()->openTag($week_form); ?>
		<div class="form-group">
			<?php echo $this->formRow($this->week_form->get('EMP_UUID')); ?>
			<?php echo $this->formRow($this->week_form->get('WORK_WEEK')); ?>
			<?php echo $this->formRow($this->week_form->get('SECURITY')); ?>
			<?php echo $this->formRow($this->week_form->get('SUBMIT')); ?>
		</div>
		<?php echo $this->form()->closeTag($week_form); ?>
	</div>
</div>

<?php 
echo $this->partial('base/subtable',[
    'title' => 'Departments',
    'data' => $this->data,
    'primary_key' => 'UUID',
    'route' => 'dashboard/dept',
    'params' => [
        [
            'action' => 'dept',
            'label' => 'Open Department',
            'route' => 'dashboard/dept',
            'key' => 'UUID',
        ],
    ],
]); 
?>


<div class="row">
	<div class="col" style="max-height: 350px; overflow-y: auto;">
    	<?php echo $this->partial('report/context', [
    	    'title' => 'Reports',
    	    'data' => $this->reports,
    	    'primary_key' => 'UUID',
    	    'route' => 'custom-report',
    	    'params' => [
    	        [
    	            'key' => 'UUID',
    	            'action' => 'view',
    	            'route' => 'custom-report',
    	            'label' => 'View',
    	            'num_vars' => 1,
    	            'vars' => [
    	                'FIELD0' => 'time_cards.WORK_WEEK',
    	                'VALUE0' => $this->work_week,
    	            ],
    	        ],
    	    ],
    	])?>
	</div>
</div>