<div class="row">
	<div class="col-6">
		<h1>Department Dashboard</h1>
	</div>
	
	<!-- Add Employee Form -->
	<div class="col-3">
		<?php $this->find_employee_form->setAttribute('action', $this->url('timecard/timesheet', ['uuid' => NULL, 'week' => $this->work_week], NULL, TRUE)); ?>
		<?php $this->find_employee_form->prepare(); ?>
		<?php echo $this->form()->openTag($this->find_employee_form); ?>
		<div class="form-group">
			<?php echo $this->bsFormSelectButtonRow($this->find_employee_form->get('UUID'), $this->find_employee_form->get('BUTTON'), NULL, NULL, 'bsFormSelectButton'); ?>
			<?php echo $this->formRow($this->find_employee_form->get('SECURITY')); ?>
			<?php echo $this->formRow($this->find_employee_form->get('SUBMIT')); ?>
		</div>
		<?php echo $this->form()->closeTag($this->find_employee_form); ?>
	</div>
	
	<div class="col-3">
		<?php $week_form->setAttribute('action', $this->url('dashboard/dept', [], NULL, TRUE)); ?>
		<?php $week_form->prepare(); ?>
		<?php echo $this->form()->openTag($week_form); ?>
		<div class="form-group">
			<?php echo $this->formRow($this->week_form->get('EMP_UUID')); ?>
			<?php echo $this->formRow($this->week_form->get('WORK_WEEK')); ?>
			<?php echo $this->formRow($this->week_form->get('SECURITY')); ?>
			<?php echo $this->formRow($this->week_form->get('SUBMIT')); ?>
		</div>
		<?php echo $this->form()->closeTag($week_form); ?>
	</div>
</div>


<?php $title = $this->dept->NAME; ?>
<div class="row">
	<div class="col">
		<?php echo $this->partial('dept/dashboard', [
		    'title' => $title,
		    'data' => $this->employees,
		    'primary_key' => 'UUID',
		    'route' => 'timecard/timesheet',
		    'role' => $roles,
		    'acl_service' => $acl_service,
		    'params' => [
		        [
    		        'action' => 'timesheet',
    		        'label' => 'Open Timesheet',
    		        'route' => 'timecard/timesheet',
    		        'key' => 'UUID',
	            ],
		        [
		            'action' => 'active',
		            'label' => 'Unsubmit',
		            'route' => 'timecard/secure_signatures',
		            'key' => 'Timecard',
		        ],
		        [
		            'action' => 'prepare',
		            'label' => 'Prepare',
		            'route' => 'timecard/secure_signatures',
		            'key' => 'Timecard',
		        ],
		        [
		            'action' => 'approve',
		            'label' => 'Approve',
		            'route' => 'timecard/secure_signatures',
		            'key' => 'Timecard',
		        ],
		        [
		            'action' => 'complete',
		            'label' => 'Complete',
		            'route' => 'timecard/secure_signatures',
		            'key' => 'Timecard',
		        ],
		    ],
		]);?>
	</div>
</div>

<div class="row">
	<div class="col" style="max-height: 350px; overflow-y: auto;">
    	<?php echo $this->partial('report/context', [
    	    'title' => 'Reports',
    	    'data' => $this->reports,
    	    'primary_key' => 'UUID',
//     	    'route' => 'reports/default',
    	    'route' => 'custom-report',
    	    'params' => [
    	        [
    	            'key' => 'UUID',
    	            'action' => 'view',
//     	            'route' => 'reports/default',
                    'route' => 'custom-report',
    	            'label' => 'View',
    	            'num_vars' => 2,
    	            'vars' => [
    	                'FIELD0' => 'time_cards.WORK_WEEK',
    	                'VALUE0' => $this->work_week,
    	                'FIELD1' => 'employees.DEPT',
    	                'VALUE1' => $this->dept->UUID,
    	            ],
    	        ],
    	    ],
    	])?>
	</div>
</div>