<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css">
	</head>
	<body>
		<h1>Submission Reminder</h1>
		<p>Time card submissions are due by 12:00pm EDT.  Please submit your card so that Payroll receives your information in a timely manner.<p> 
	</body>
</html>
