<?php
/**
 * Passed Variables
 * form, user_entity, acl_service
 */
use Components\Form\Element\DatabaseSelect;
use Timecard\Model\TimecardLineModel;

$uuid= $form->get('UUID')->getValue();
$form->setAttribute('action', $this->url('timecard/lines', ['action' => 'update', 'uuid' => $uuid]));
$form->prepare();

echo $this->form()->openTag($form);

$paycode = $form->get('PAY_UUID');
$paycode_value_options = $paycode->getValueOptions();
$paycode_value = $paycode->getValue();

echo $this->formInput($form->get('UUID'));
echo $this->formInput($form->get('SECURITY'));
echo $this->formInput($form->get('TIMECARD_UUID'));

$cols = ['MON','TUE','WED','THU','FRI','SAT','SUN','DAYS'];
$total_paycode = 0;
?>
<div class="row">
	<!-- Paycode -->
	<div class="col" id="paycode">
		<?php echo $paycode_value_options[$paycode_value];?>
	</div>

    <!-- Days of the Week -->
	<?php foreach ($cols as $col) : ?>
		<?php $total_paycode += $form->get($col)->getValue(); ?>
			
    	<?php if ($this->acl_service->isAllowed($this->user->memberOf(TRUE), 'TIMECARD_LINE', $this->form->get('STATUS')->getValue())) : ?>
    		<div class="col" id="<?=$col?>"><?php echo $this->formInput($form->get($col));?></div>
		<?php else : ?>
    		<div class="col" id="<?=$col?>"><?php echo $form->get($col)->getValue(); ?></div>
    	<?php endif; ?>

	<?php endforeach; ?>
	
	<!-- Badge -->
	<div class="col">
		<?php 
		if ($total_paycode > 40) {
		    echo "<span class='badge text-bg-warning'>" . $total_paycode . "</span>";
		} else {
		    echo "<span class='badge text-bg-success'>" . $total_paycode . "</span>";
		}
        ?>
	</div>
	
	<!-- Functions -->
	<div class="col">
		<?php if ($this->acl_service->isAllowed($this->user->memberOf(TRUE), 'TIMECARD_LINE', $this->form->get('STATUS')->getValue())) : ?>
		<a class="btn btn-primary" href="<?php echo $this->url('timecard/lines', ['action' => 'delete', 'uuid' => $form->get('UUID')->getValue()]); ?>"><i class="fas fa-trash-alt"></i></a>
		<?php endif; ?>
	</div>
</div>
<?php echo $this->formInput($form->get('SUBMIT'));?>
<?php echo $this->form()->closeTag($form); ?>