<?php 
use Components\Form\Element\DatabaseSelect;
use Timecard\Model\TimecardLineModel;

$uuid= $form->get('UUID')->getValue();
$form->setAttribute('action', $this->url('timecard/lines', ['action' => 'update', 'uuid' => $uuid]));
$form->prepare();

echo $this->form()->openTag($form);

$paycode = $form->get('PAY_UUID');
$paycode_value_options = $paycode->getValueOptions();
$paycode_value = $paycode->getValue();

echo $this->formInput($form->get('UUID'));
echo $this->formInput($form->get('SECURITY'));
echo $this->formInput($form->get('TIMECARD_UUID'));

$cols = ['MON','TUES','WED','THURS','FRI','SAT','SUN','DAYS'];
$total_paycode = 0;
?>

<tr>
	<td><span style="white-space:nowrap"><?php echo $paycode_value_options[$paycode_value];?></span></td>
	
	<?php foreach ($cols as $col) : ?>
		<?php $total_paycode += $form->get($col)->getValue(); ?>
	
		<?php if ($form->get('STATUS')->getValue() == TimecardLineModel::SUBMITTED_STATUS && $this->role == 'APP - CHRONOS USER') : ?>
		
			<td><?php echo $form->get($col)->getValue(); ?></td>
		<?php else : ?>
			<td><?php echo $this->formInput($form->get($col));?></td>
		<?php endif; ?>
	
	<?php endforeach; ?>
	<td>
		<?php 
		if ($total_paycode > 40) {
		    echo "<span class='badge badge-warning'>" . $total_paycode . "</span>";
		} else {
		    echo "<span class='badge badge-success'>" . $total_paycode . "</span>";
		}
        ?>
	</td>
	<td>
		<a href="<?php echo $this->url('timecard/lines', ['action' => 'delete', 'uuid' => $form->get('UUID')->getValue()]); ?>"><i class="fas fa-trash-alt"></i></a>
		<?php // echo $this->formCheckbox($form->get('STATUS')); ?>
	</td>
</tr>
<?php echo $this->formInput($form->get('SUBMIT'));?>
<?php echo $this->form()->closeTag($form); ?>